### ISSUE TITLE
Update to swift 5

### ISSUE THREAD

**Issue by fury21** [seaburg/FormattedTextField#3]
Hi! 
Thank u very math for this framework. Can u update it to swift 5, because a get some errors in console when i launch app. 

 Failed to set (textMasks) user defined inspected property on (FormattedTextField.FormattedTextField): [<FormattedTextField.FormattedTextField 0x7fc05c86e200> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key textMasks.

Thank u!

**Comment by seaburg** [comment]
Hi @fury21! Warning not related to swift version
`FormattedTextField.textMasks` has been remove at `0.5` version of the library. You can try to find and remove user defined attributes in xibs/storyboards to fix warnings in your project (This problem also exists in the example of project, i will fix it. Thanks!)

In any case, i will soon update library to swift 5

**Comment by seaburg** [comment]
Fixed and migrated example (The library has already been migrated to swift 5)

Thanks!
